import React from 'react'

const Midsection = () => {
  return (
    <div style={{padding:"20px"}}>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex, necessitatibus quas nobis minus in ipsum voluptates dolores error accusamus veniam velit, culpa sint quis dolorem delectus at unde dolore! Hic, non aliquam? Minima exercitationem numquam quo! Eveniet nemo maxime blanditiis quam quis nulla sint itaque tempora cupiditate asperiores, ipsum modi impedit sequi vero corporis voluptates eum et architecto placeat necessitatibus ab possimus. Quos dolor perspiciatis nostrum culpa minima. Ratione delectus doloremque omnis maiores exercitationem, in velit consectetur veritatis commodi sit magni pariatur ut sapiente tempore quasi modi vitae laudantium impedit consequatur ad quisquam! Voluptatem aliquam harum nesciunt omnis, in optio! Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia nobis voluptatum incidunt commodi excepturi ipsam itaque quisquam neque nesciunt rerum unde ea, quo maxime debitis! Dolore modi quas quam impedit dolorum! Sit adipisci corporis voluptas soluta animi aliquam expedita quod veniam consequatur ex et assumenda quisquam explicabo dicta ipsam, nemo, laudantium asperiores rem labore nihil nobis ullam eius veritatis magni! Debitis exercitationem, ipsam, odit beatae animi quam sapiente quod quisquam veniam excepturi recusandae cumque eos nam obcaecati minus nobis iste, repudiandae tenetur qui tempore? Sequi exercitationem vitae autem voluptatibus modi aliquam aut officia. Est sunt quaerat illum nihil quas ipsam error eveniet, quia dignissimos porro beatae ea natus perspiciatis? Voluptatem eaque facilis nam error ducimus, voluptate eius, asperiores delectus sequi eos harum reiciendis, doloribus numquam repellat reprehenderit. Explicabo illo quidem dolore possimus itaque beatae quod at cumque exercitationem nesciunt numquam, porro fugit sed vitae saepe dolorum architecto, eum accusamus, soluta officiis dolores consequuntur omnis. Doloremque culpa numquam, explicabo eos aliquid modi deserunt nisi et, ad rem similique iusto expedita ex eligendi dolores hic. Rem assumenda fugiat, repellat, numquam tempore sit dignissimos repudiandae, quo sequi neque rerum obcaecati? Atque ex, nemo eos ipsam ullam, earum quia modi repellendus itaque temporibus reiciendis.
    </div>
  )
}

export default Midsection
